import type cytoscape from 'cytoscape';

export const layouts: Record<string, object> = {
  'cose-bilkent': {
    name: 'cose-bilkent',
    quality: 'default',
    nodeDimensionsIncludeLabels: true,
    animate: 'end',
    animationDuration: 500,
    fit: true,
    padding: 50,
    idealEdgeLength: 100,
    edgeElasticity: 0.45,
    nestingFactor: 0.1,
    gravity: 0.25,
    numIter: 2500,
    tile: true,
    tilingPaddingVertical: 20,
    tilingPaddingHorizontal: 20,
    gravityRangeCompound: 1.5,
    gravityCompound: 1.0,
    gravityRange: 3.8,
  },
  concentric: {
    name: 'concentric',
    fit: true,
    padding: 50,
    animate: true,
    animationDuration: 500,
    concentric: (node: cytoscape.NodeSingular) => (node.data('isGateway') ? 10 : node.degree()),
    levelWidth: () => 2,
    minNodeSpacing: 60,
  },
  grid: {
    name: 'grid',
    fit: true,
    padding: 50,
    animate: true,
    animationDuration: 500,
    rows: undefined,
    cols: undefined,
    avoidOverlap: true,
    avoidOverlapPadding: 20,
  },
  circle: {
    name: 'circle',
    fit: true,
    padding: 50,
    animate: true,
    animationDuration: 500,
    avoidOverlap: true,
    spacingFactor: 1.5,
  },
};
